<a href="https://colab.research.google.com/github/paras-lehana/utils/blob/master/ml/guass_jordan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

Define Augmented Matrix with last columns as constants. 

In [241]:
matrix = np.array([[0,1,2],[1,2,1],[2,7,8]])
n,p = np.shape(matrix)

print("\n\n-----------------\n\nMatrix A:\n")
print(matrix[:,:p-1])



-----------------

Matrix A:

[[0 1]
 [1 2]
 [2 7]]


Checking if a matrix is in its Row Echelon Form. The conditions are:

1.   All nonzero rows are above any rows of all zeros. (If not satisfied, returns -1)
2.   Each leading entry (i.e. first/leftmost nonzero entry) also called a pivot, of a non
zero row is in a column to the right of the leading entry of the row above it. (If not satisfied, returns -2)
3.   All entries in a column below a leading entry are zero. (If not satisfied, returns -3)

If all of three all satisfied, `isREF()` returns 1. 

In [0]:
def isREF(matrix):
  
  n,p = np.shape(matrix)
  lastZeroRow = n
  lastNonZeroRow = 0
  
  for rownum, row in enumerate(matrix):
    
    #Checking for (1): If the last non-zero row is above the first all-zero row.
    for ele in row:
      if(ele != 0):
        lastNonZeroRow = rownum
        break
      
    if(lastNonZeroRow != rownum):
      lastZeroRow = rownum
    
  if(lastZeroRow <= lastNonZeroRow):
    return -1;

  #Checking for (2): Current row's pivot should be located to the right of upper row's pivot.
  
  leadingColumnOfAboveRow = -1
  
  for row in matrix:
    for colnum, ele in enumerate(row):
      if(ele != 0):
        if(colnum <= leadingColumnOfAboveRow):
          return -2
        leadingColumnOfAboveRow = colnum
        break
       
  
  #Checking for (3): Each row's pivot should not have any non-zero entry below itself
  
  for rownum, row in enumerate(matrix):
      for colnum, ele in enumerate(row):
        if(ele != 0):
          if(np.any(matrix[rownum+1:,colnum])):
            return -3
          break
          
  return 1;
   
   
# matrixTest = np.array([[1,2,1],[0,1,2],[0,0,0]])
# print("\n\n-----------------\n\nMatrix Test:\n")
# print(matrixTest)
#print(isREF(matrixTest))

Checking if a matrix is in its ***Reduced*** Row Echelon Form. The conditions are:

1.   The matrix is in row echelon form (If not satisfied, returns -1, -2 or -3 depending on the unsatisfied condition for REF)
2.   The leading entry in each row is the only non-zero entry in its column. (If not satisfied, returns -4)
3.   All the leading entries should be equal to 1. (If not satisfied, returns -5)

If all of three all satisfied, `isRREF()` returns 1. 

In [0]:

def isRREF(matrix):
  
  #Checking for (1): If the matrix in its Row Echelon Form.
  
  if(isREF(matrix) != 1):
    return isREF(matrix)
  
  #Checking for (2): Each row's pivot should not have any non-zero entry above itself
  
  for rownum, row in enumerate(matrix):
      for colnum, ele in enumerate(row):
        if(ele != 0):
          if(np.any(matrix[:rownum,colnum])):
            return -4
          break
  
  #Checking for (3): Each row's pivot should be 1.
  
  for rownum, row in enumerate(matrix):
      for colnum, ele in enumerate(row):
        if(ele != 0):
          if(ele != 1):
            return -5
          break
  
  return 1


# matrixTest = np.array([[1,2,0,0],[0,0,1,0],[0,0,0,1],[0,0,0,0]])
# print("\n\n-----------------\n\nMatrix Test:\n")
# print(matrixTest)
# print(isRREF(matrixTest))

*Pivot Element is the first non-zero element in the given vector. If `ignoreIndex` is provided, the pivot is computed ignoring indexes till `ignoreIndex`. You can pass both row and column vector. In case pivot is not found, returns -1. Otherwise, returns index and the element.* 

In [0]:
def pivot(column,ignoreIndex=0):
  for index, ele in enumerate(column[ignoreIndex:],start=ignoreIndex):
    if(ele != 0):
      return index, ele
  return -1, -1

Program to convert matrix to Row Echelon Form. Use function ref() if you don't want to output steps. The steps to convert are as follows:


1.   Find the pivot of the matrix (the first non-zero entry in the given column of the matrix).
2.   Apply row operations and bring the row with pivot element at the top of the matrix.
3.   Now we must make the pivot element as 1(not necessary, but makes computations easier),
so for that multiply the row with pivot element with the inverse of the pivot element.
4.   Add multiples of the pivot row to each of the lower rows, so every element in the pivot
column of the lower rows equals 0.
5.   Repeat the procedure from Step 1 to 5 above, ignoring previous pivot rows.
6.   Continue until there are no more pivots to be processed.

In [245]:
swapRow = 0

n,p = np.shape(matrix)

for colnum, col in enumerate(matrix.T):
  
  print("\n\n-----------------\n-----------------\nCurrent Column No.: ",colnum)
  
  if(isRREF(matrix[:,:p-1]) == 1):
    break
  
  print("\n\n-----------------\n\nCurrent Column:", col)
  
  pivotRow, pivotElement = pivot(col,swapRow)
  
  print("Pivot Element: ", pivotElement)
  
  matrix[[swapRow, pivotRow]] = matrix[[pivotRow, swapRow]]
  
  print("\n\n-----------------\n\nMatrix after Swapping Pivot Row:\n")
  print(matrix)
  
  if(pivotElement != 1):
    matrix[swapRow] = [ele/pivotElement for ele in matrix[swapRow]]
  
  print("\n\n-----------------\n\nMatrix after making Pivot Element 1:\n")
  print(matrix)
  
  for rownum, ele in enumerate(col[swapRow+1:],start=swapRow+1):
    if(ele != 0):
      matrix[rownum] = [rowEle-ele*matrix[swapRow,col] for col,rowEle in enumerate(matrix[rownum])]
      
      
  print("\n\n-----------------\n\nMatrix after making elements below Pivot Element 0:\n")
  print(matrix)
  
  swapRow = swapRow+1
  
  
print("\n\n-----------------\n\nMatrix after Row Echelon Form:\n")
print(matrix)

def ref(matrix):
  
  swapRow = 0

  for colnum, col in enumerate(matrix.T): #(5): swapRow keeps the count of ignored rows from start.

    if(isREF(matrix[:,:p-1]) == 1):
      break

    pivotRow, pivotElement = pivot(col,swapRow)
    matrix[[swapRow, pivotRow]] = matrix[[pivotRow, swapRow]] #(2): Swapping pivot row with the first row after ignored rows.

    if(pivotElement != 1):
      matrix[swapRow] = [ele/pivotElement for ele in matrix[swapRow]] #(3): Making each element of pivot row (after swapping) equal to one.

    for rownum, ele in enumerate(col[swapRow+1:],start=swapRow+1):
      if(ele != 0):
        matrix[rownum] = [rowEle-ele*matrix[swapRow,col] for col,rowEle in enumerate(matrix[rownum])] #(4): Making elements below in the column of pivot of current row equal to zero.

    swapRow = swapRow+1

    return matrix
  




-----------------
-----------------
Current Column No.:  0


-----------------

Current Column: [0 1 2]
Pivot Element:  1


-----------------

Matrix after Swapping Pivot Row:

[[1 2 1]
 [0 1 2]
 [2 7 8]]


-----------------

Matrix after making Pivot Element 1:

[[1 2 1]
 [0 1 2]
 [2 7 8]]


-----------------

Matrix after making elements below Pivot Element 0:

[[1 2 1]
 [0 1 2]
 [0 3 6]]


-----------------
-----------------
Current Column No.:  1


-----------------

Current Column: [2 1 3]
Pivot Element:  1


-----------------

Matrix after Swapping Pivot Row:

[[1 2 1]
 [0 1 2]
 [0 3 6]]


-----------------

Matrix after making Pivot Element 1:

[[1 2 1]
 [0 1 2]
 [0 3 6]]


-----------------

Matrix after making elements below Pivot Element 0:

[[1 2 1]
 [0 1 2]
 [0 0 0]]


-----------------
-----------------
Current Column No.:  2


-----------------

Current Column: [1 2 0]
Pivot Element:  -1


-----------------

Matrix after Swapping Pivot Row:

[[1 2 1]
 [0 1 2]
 [0 0 0]]


Program to convert matrix to **Reduced** Row Echelon Form. Use function `rref()` if you don't want to output steps. The steps to convert are as follows:



1.   Convert to Row Echelon Form first.
2.   Identify the last row having a pivot equal to 1, and let this be the pivot row.
3.   Add multiples of the pivot row to each of the upper rows, until every element above
the pivot equals 0.
4.   Moving up the matrix, repeat this process for each row.

In [246]:
for rownum in reversed(range(n)):
  print("\n\n-----------------\n-----------------\nCurrent Row No.: ", rownum)
  
  if(isRREF(matrix[:,:p-1]) == 1):
    break
    
  print("\n\n-----------------\n\nCurrent Row:", matrix[rownum,:])
  
  pivotColumn, pivotElement = pivot(matrix[rownum,:])
  
  print("Pivot Element: ", pivotElement)
  
  if(pivotColumn == -1 or rownum == 0):
    continue
    
  for upperRownum, ele in enumerate(matrix[:rownum,pivotColumn]):
    if(ele != 0):
      matrix[upperRownum] = [rowEle-ele*matrix[rownum,col] for col,rowEle in enumerate(matrix[upperRownum])]
      
  print("\n\n-----------------\n\nMatrix after making elements above Pivot Element 0:\n")
  print(matrix)
  
  
print("\n\n-----------------\n\nMatrix after Reduced Row Echelon Form:\n")
print(matrix)



def rref(matrix):
  matrix = ref(matrix[:,:p-1]) #(1): Convert to ref.
  
  for rownum in reversed(range(n)): #(4): Itering from last row, columns in order

    if(isRREF(matrix) == 1):
      break

    pivotColumn, pivotElement = pivot(matrix[rownum,:]) #(2): Calculating pivot element of current column

    print("Pivot Element: ", pivotElement)

    if(pivotColumn == -1 or rownum == 0): #In case pivot element is not found or we have reached to the first row
      continue

    for upperRownum, ele in enumerate(matrix[:rownum,pivotColumn]):
      if(ele != 0):
        matrix[upperRownum] = [rowEle-ele*matrix[rownum,col] for col,rowEle in enumerate(matrix[upperRownum])] #(3): Making elements above in the column of pivot of current row equal to zero.

    return matrix
  



-----------------
-----------------
Current Row No.:  2


-----------------

Current Row: [0 0 0]
Pivot Element:  -1


-----------------
-----------------
Current Row No.:  1


-----------------

Current Row: [0 1 2]
Pivot Element:  1


-----------------

Matrix after making elements above Pivot Element 0:

[[ 1  0 -3]
 [ 0  1  2]
 [ 0  0  0]]


-----------------
-----------------
Current Row No.:  0


-----------------

Matrix after Reduced Row Echelon Form:

[[ 1  0 -3]
 [ 0  1  2]
 [ 0  0  0]]


Now that we are ready with rref of Matrix, we can deduce solution as follows:


1.   If there are all non-zero rows in the matrix leaving last column, infinite solutions.
2.   If not (1) and there are one or more non-zero rows, no solution.
3.   If there are no non-zero row, solution is generated using the last column.

In [247]:
for rownum in range(n):
  nosol = 0
  
  if(matrix[rownum,rownum] == 1):
    print(chr(ord('a')+rownum),': ',matrix[rownum,p-1])
  else:
    nosol = nosol + 1
    
if(nosol == n):
  print("\nInfinite Solutions")
elif(nosol != 0):
  print("\nNo Solution")

a :  -3
b :  2

No Solution
