<a href="https://colab.research.google.com/github/paras-lehana/utils/blob/master/ml/SVD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

*   **Import** `numpy` for defining arrays and doing array operations
*   **Import** `linalg` in `numpy` for doing linear algebra over arrays - like computing eigen values

In [0]:
import numpy as np
from numpy import linalg as la

import math

*The default function eig doesn't neccessary gives eigen values or vectors in order. So I have created a wrapper that sorts the values and vectors in descending order. This is requirement for SVD decomposition to U, S and V arrays.*

In [0]:
def eigen(matrix):
  
  eigenValues, eigenVectors = la.eig(matrix)

  idx = eigenValues.argsort()[::-1]
  eigenValues = eigenValues[idx]
  eigenVectors = eigenVectors[:,idx]
  
  return eigenValues, eigenVectors
  


*   Define array whose SVD composition is needed. 
*   Calculate dimension which would be needed to construct middle S vector (n x p)



In [0]:
#matrixA = np.array([[1,0,1,0],[0,1,0,1]])
matrixA = np.array([[2,4],[1,3],[0,0],[0,0]])
#matrixA = np.array([[5,5],[-1,7]])
#matrixA = np.array([[3,1,1],[-1,3,1]])

#matrixA = np.array([[4,0],[3,-5]])
n,p = np.shape(matrixA)

**Calculate AᵀA and AAᵀ.** 

In [0]:
print("\n\n-----------------\n\nMatrix A:\n")
print(matrixA)

matrixAAT = np.dot(matrixA,matrixA.transpose())
matrixATA = np.dot(matrixA.transpose(),matrixA)

print("\n\n-----------------\n\nMatrix AAT:\n")
print(matrixAAT)
print("\n\n-----------------\n\nMatrix ATA:\n")
print(matrixATA)



-----------------

Matrix A:

[[2 4]
 [1 3]
 [0 0]
 [0 0]]


-----------------

Matrix AAT:

[[20 14  0  0]
 [14 10  0  0]
 [ 0  0  0  0]
 [ 0  0  0  0]]


-----------------

Matrix ATA:

[[ 5 11]
 [11 25]]


*Eigen vector of AAᵀ makes the column of vector U.*

In [0]:
eigenValues, eigenVectors = eigen(matrixAAT)

matrixU = eigenVectors
print("\nEigen Values:\n")
print(eigenValues)

print("\n\n-----------------\n\nMatrix U:\n")
print(matrixU)


Eigen Values:

[29.86606875  0.13393125  0.          0.        ]


-----------------

Matrix U:

[[ 0.81741556 -0.57604844  0.          0.        ]
 [ 0.57604844  0.81741556  0.          0.        ]
 [ 0.          0.          0.          1.        ]
 [ 0.          0.          1.          0.        ]]


*We need to fill square root of each eigen value (either from AᵀA or AAᵀ) as diagonal elements of vector S. Reshape is needed to transform the eigenValue 1D matrix into a diagonal matrix of n x p. Vectorize runs over each element of the matrix and (here) replaces it with its square root.*

In [0]:
matrixS = np.vectorize(math.sqrt, otypes=[float])(eigenValues.reshape(n,1)*np.eye(n,M=p, dtype=int))
print("\n\n-----------------\n\nMatrix S:\n")
print(matrixS)



-----------------

Matrix S:

[[5.4649857  0.        ]
 [0.         0.36596619]
 [0.         0.        ]
 [0.         0.        ]]


*Eigen vector of AAᵀ makes the column of vector U.*


In [0]:
eigenValues, eigenVectors = eigen(matrixATA)

matrixV = eigenVectors
print("\nEigen Values:\n")
print(eigenValues)

print("\n\n-----------------\n\nMatrix V:\n")
print(matrixV)


Eigen Values:

[29.86606875  0.13393125]


-----------------

Matrix V:

[[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]


---

*  Comparing the product of decompostion with the original matrix.

*  Also, comparing U, S and V with inbuilt svd function of linalg.

---




In [0]:
matrixSVD = matrixU.dot(matrixS).dot(matrixV.transpose())
print("\n\n-----------------\n\nMatrix SVD = A ?:\n")
print(matrixSVD)

print("\n\n-----------------\n\nMatrix SVD by formula:\n")
u,s,vt = la.svd(matrixA)

print("-----------------\n\nMatrix U:\n")
print(u);

print("-----------------\n\nMatrix S:\n")
print(s);

print("\n\n-----------------\n\nMatrix V:\n")
print(v);




-----------------

Matrix SVD = A ?:

[[-1.61441471 -4.17057132]
 [-1.54714743 -2.75795846]
 [ 0.          0.        ]
 [ 0.          0.        ]]


-----------------

Matrix SVD by formula:

-----------------

Matrix U:

[[-0.81741556 -0.57604844  0.          0.        ]
 [-0.57604844  0.81741556  0.          0.        ]
 [ 0.          0.          1.          0.        ]
 [ 0.          0.          0.          1.        ]]
-----------------

Matrix S:

[5.4649857  0.36596619]


-----------------

Matrix V:

[[ 0.70710678  0.          0.70710678  0.        ]
 [ 0.          0.70710678  0.          0.70710678]
 [-0.70710678  0.          0.70710678  0.        ]
 [ 0.         -0.70710678  0.          0.70710678]]
